// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: org/xrpl/rpc/v1/get_ledger_diff.proto

#include "org/xrpl/rpc/v1/get_ledger_diff.pb.h"
#include "org/xrpl/rpc/v1/get_ledger_diff.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace org {
namespace xrpl {
namespace rpc {
namespace v1 {

}  // namespace org
}  // namespace xrpl
}  // namespace rpc
}  // namespace v1

