// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/xrpl/rpc/v1/get_ledger_data.proto

#include "org/xrpl/rpc/v1/get_ledger_data.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace org {
namespace xrpl {
namespace rpc {
namespace v1 {
PROTOBUF_CONSTEXPR GetLedgerDataRequest::GetLedgerDataRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.marker_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.end_marker_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.client_ip_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.user_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ledger_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetLedgerDataRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetLedgerDataRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetLedgerDataRequestDefaultTypeInternal() {}
  union {
    GetLedgerDataRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetLedgerDataRequestDefaultTypeInternal _GetLedgerDataRequest_default_instance_;
PROTOBUF_CONSTEXPR GetLedgerDataResponse::GetLedgerDataResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ledger_hash_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.marker_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ledger_objects_)*/nullptr
  , /*decltype(_impl_.ledger_index_)*/0u
  , /*decltype(_impl_.is_unlimited_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetLedgerDataResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetLedgerDataResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetLedgerDataResponseDefaultTypeInternal() {}
  union {
    GetLedgerDataResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetLedgerDataResponseDefaultTypeInternal _GetLedgerDataResponse_default_instance_;
}  // namespace v1
}  // namespace rpc
}  // namespace xrpl
}  // namespace org
static ::_pb::Metadata file_level_metadata_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto = nullptr;

const uint32_t TableStruct_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerDataRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerDataRequest, _impl_.marker_),
  PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerDataRequest, _impl_.ledger_),
  PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerDataRequest, _impl_.end_marker_),
  PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerDataRequest, _impl_.client_ip_),
  PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerDataRequest, _impl_.user_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerDataResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerDataResponse, _impl_.ledger_index_),
  PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerDataResponse, _impl_.ledger_hash_),
  PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerDataResponse, _impl_.ledger_objects_),
  PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerDataResponse, _impl_.marker_),
  PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerDataResponse, _impl_.is_unlimited_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::org::xrpl::rpc::v1::GetLedgerDataRequest)},
  { 11, -1, -1, sizeof(::org::xrpl::rpc::v1::GetLedgerDataResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::org::xrpl::rpc::v1::_GetLedgerDataRequest_default_instance_._instance,
  &::org::xrpl::rpc::v1::_GetLedgerDataResponse_default_instance_._instance,
};

const char descriptor_table_protodef_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n%org/xrpl/rpc/v1/get_ledger_data.proto\022"
  "\017org.xrpl.rpc.v1\032\034org/xrpl/rpc/v1/ledger"
  ".proto\"\215\001\n\024GetLedgerDataRequest\022\016\n\006marke"
  "r\030\001 \001(\014\0220\n\006ledger\030\002 \001(\0132 .org.xrpl.rpc.v"
  "1.LedgerSpecifier\022\022\n\nend_marker\030\003 \001(\014\022\021\n"
  "\tclient_ip\030\004 \001(\t\022\014\n\004user\030\006 \001(\t\"\243\001\n\025GetLe"
  "dgerDataResponse\022\024\n\014ledger_index\030\001 \001(\r\022\023"
  "\n\013ledger_hash\030\002 \001(\014\0229\n\016ledger_objects\030\003 "
  "\001(\0132!.org.xrpl.rpc.v1.RawLedgerObjects\022\016"
  "\n\006marker\030\004 \001(\014\022\024\n\014is_unlimited\030\007 \001(\010B\023\n\017"
  "org.xrpl.rpc.v1P\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto_deps[1] = {
  &::descriptor_table_org_2fxrpl_2frpc_2fv1_2fledger_2eproto,
};
static ::_pbi::once_flag descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto = {
    false, false, 425, descriptor_table_protodef_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto,
    "org/xrpl/rpc/v1/get_ledger_data.proto",
    &descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto_once, descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto_deps, 1, 2,
    schemas, file_default_instances, TableStruct_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto::offsets,
    file_level_metadata_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto, file_level_enum_descriptors_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto,
    file_level_service_descriptors_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto_getter() {
  return &descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto(&descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto);
namespace org {
namespace xrpl {
namespace rpc {
namespace v1 {

// ===================================================================

class GetLedgerDataRequest::_Internal {
 public:
  static const ::org::xrpl::rpc::v1::LedgerSpecifier& ledger(const GetLedgerDataRequest* msg);
};

const ::org::xrpl::rpc::v1::LedgerSpecifier&
GetLedgerDataRequest::_Internal::ledger(const GetLedgerDataRequest* msg) {
  return *msg->_impl_.ledger_;
}
void GetLedgerDataRequest::clear_ledger() {
  if (GetArenaForAllocation() == nullptr && _impl_.ledger_ != nullptr) {
    delete _impl_.ledger_;
  }
  _impl_.ledger_ = nullptr;
}
GetLedgerDataRequest::GetLedgerDataRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:org.xrpl.rpc.v1.GetLedgerDataRequest)
}
GetLedgerDataRequest::GetLedgerDataRequest(const GetLedgerDataRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetLedgerDataRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.marker_){}
    , decltype(_impl_.end_marker_){}
    , decltype(_impl_.client_ip_){}
    , decltype(_impl_.user_){}
    , decltype(_impl_.ledger_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.marker_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.marker_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_marker().empty()) {
    _this->_impl_.marker_.Set(from._internal_marker(), 
      _this->GetArenaForAllocation());
  }
  _impl_.end_marker_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.end_marker_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_end_marker().empty()) {
    _this->_impl_.end_marker_.Set(from._internal_end_marker(), 
      _this->GetArenaForAllocation());
  }
  _impl_.client_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.client_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_client_ip().empty()) {
    _this->_impl_.client_ip_.Set(from._internal_client_ip(), 
      _this->GetArenaForAllocation());
  }
  _impl_.user_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_user().empty()) {
    _this->_impl_.user_.Set(from._internal_user(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_ledger()) {
    _this->_impl_.ledger_ = new ::org::xrpl::rpc::v1::LedgerSpecifier(*from._impl_.ledger_);
  }
  // @@protoc_insertion_point(copy_constructor:org.xrpl.rpc.v1.GetLedgerDataRequest)
}

inline void GetLedgerDataRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.marker_){}
    , decltype(_impl_.end_marker_){}
    , decltype(_impl_.client_ip_){}
    , decltype(_impl_.user_){}
    , decltype(_impl_.ledger_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.marker_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.marker_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.end_marker_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.end_marker_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.client_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.client_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.user_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GetLedgerDataRequest::~GetLedgerDataRequest() {
  // @@protoc_insertion_point(destructor:org.xrpl.rpc.v1.GetLedgerDataRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetLedgerDataRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.marker_.Destroy();
  _impl_.end_marker_.Destroy();
  _impl_.client_ip_.Destroy();
  _impl_.user_.Destroy();
  if (this != internal_default_instance()) delete _impl_.ledger_;
}

void GetLedgerDataRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetLedgerDataRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:org.xrpl.rpc.v1.GetLedgerDataRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.marker_.ClearToEmpty();
  _impl_.end_marker_.ClearToEmpty();
  _impl_.client_ip_.ClearToEmpty();
  _impl_.user_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.ledger_ != nullptr) {
    delete _impl_.ledger_;
  }
  _impl_.ledger_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetLedgerDataRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes marker = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_marker();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .org.xrpl.rpc.v1.LedgerSpecifier ledger = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_ledger(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes end_marker = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_end_marker();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string client_ip = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_client_ip();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "org.xrpl.rpc.v1.GetLedgerDataRequest.client_ip"));
        } else
          goto handle_unusual;
        continue;
      // string user = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_user();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "org.xrpl.rpc.v1.GetLedgerDataRequest.user"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetLedgerDataRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:org.xrpl.rpc.v1.GetLedgerDataRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes marker = 1;
  if (!this->_internal_marker().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_marker(), target);
  }

  // .org.xrpl.rpc.v1.LedgerSpecifier ledger = 2;
  if (this->_internal_has_ledger()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::ledger(this),
        _Internal::ledger(this).GetCachedSize(), target, stream);
  }

  // bytes end_marker = 3;
  if (!this->_internal_end_marker().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_end_marker(), target);
  }

  // string client_ip = 4;
  if (!this->_internal_client_ip().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_client_ip().data(), static_cast<int>(this->_internal_client_ip().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "org.xrpl.rpc.v1.GetLedgerDataRequest.client_ip");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_client_ip(), target);
  }

  // string user = 6;
  if (!this->_internal_user().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_user().data(), static_cast<int>(this->_internal_user().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "org.xrpl.rpc.v1.GetLedgerDataRequest.user");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_user(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:org.xrpl.rpc.v1.GetLedgerDataRequest)
  return target;
}

size_t GetLedgerDataRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:org.xrpl.rpc.v1.GetLedgerDataRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes marker = 1;
  if (!this->_internal_marker().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_marker());
  }

  // bytes end_marker = 3;
  if (!this->_internal_end_marker().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_end_marker());
  }

  // string client_ip = 4;
  if (!this->_internal_client_ip().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_client_ip());
  }

  // string user = 6;
  if (!this->_internal_user().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_user());
  }

  // .org.xrpl.rpc.v1.LedgerSpecifier ledger = 2;
  if (this->_internal_has_ledger()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.ledger_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetLedgerDataRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetLedgerDataRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetLedgerDataRequest::GetClassData() const { return &_class_data_; }


void GetLedgerDataRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetLedgerDataRequest*>(&to_msg);
  auto& from = static_cast<const GetLedgerDataRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:org.xrpl.rpc.v1.GetLedgerDataRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_marker().empty()) {
    _this->_internal_set_marker(from._internal_marker());
  }
  if (!from._internal_end_marker().empty()) {
    _this->_internal_set_end_marker(from._internal_end_marker());
  }
  if (!from._internal_client_ip().empty()) {
    _this->_internal_set_client_ip(from._internal_client_ip());
  }
  if (!from._internal_user().empty()) {
    _this->_internal_set_user(from._internal_user());
  }
  if (from._internal_has_ledger()) {
    _this->_internal_mutable_ledger()->::org::xrpl::rpc::v1::LedgerSpecifier::MergeFrom(
        from._internal_ledger());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetLedgerDataRequest::CopyFrom(const GetLedgerDataRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:org.xrpl.rpc.v1.GetLedgerDataRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetLedgerDataRequest::IsInitialized() const {
  return true;
}

void GetLedgerDataRequest::InternalSwap(GetLedgerDataRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.marker_, lhs_arena,
      &other->_impl_.marker_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.end_marker_, lhs_arena,
      &other->_impl_.end_marker_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.client_ip_, lhs_arena,
      &other->_impl_.client_ip_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.user_, lhs_arena,
      &other->_impl_.user_, rhs_arena
  );
  swap(_impl_.ledger_, other->_impl_.ledger_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetLedgerDataRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto_getter, &descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto_once,
      file_level_metadata_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto[0]);
}

// ===================================================================

class GetLedgerDataResponse::_Internal {
 public:
  static const ::org::xrpl::rpc::v1::RawLedgerObjects& ledger_objects(const GetLedgerDataResponse* msg);
};

const ::org::xrpl::rpc::v1::RawLedgerObjects&
GetLedgerDataResponse::_Internal::ledger_objects(const GetLedgerDataResponse* msg) {
  return *msg->_impl_.ledger_objects_;
}
void GetLedgerDataResponse::clear_ledger_objects() {
  if (GetArenaForAllocation() == nullptr && _impl_.ledger_objects_ != nullptr) {
    delete _impl_.ledger_objects_;
  }
  _impl_.ledger_objects_ = nullptr;
}
GetLedgerDataResponse::GetLedgerDataResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:org.xrpl.rpc.v1.GetLedgerDataResponse)
}
GetLedgerDataResponse::GetLedgerDataResponse(const GetLedgerDataResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetLedgerDataResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ledger_hash_){}
    , decltype(_impl_.marker_){}
    , decltype(_impl_.ledger_objects_){nullptr}
    , decltype(_impl_.ledger_index_){}
    , decltype(_impl_.is_unlimited_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.ledger_hash_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ledger_hash_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ledger_hash().empty()) {
    _this->_impl_.ledger_hash_.Set(from._internal_ledger_hash(), 
      _this->GetArenaForAllocation());
  }
  _impl_.marker_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.marker_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_marker().empty()) {
    _this->_impl_.marker_.Set(from._internal_marker(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_ledger_objects()) {
    _this->_impl_.ledger_objects_ = new ::org::xrpl::rpc::v1::RawLedgerObjects(*from._impl_.ledger_objects_);
  }
  ::memcpy(&_impl_.ledger_index_, &from._impl_.ledger_index_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_unlimited_) -
    reinterpret_cast<char*>(&_impl_.ledger_index_)) + sizeof(_impl_.is_unlimited_));
  // @@protoc_insertion_point(copy_constructor:org.xrpl.rpc.v1.GetLedgerDataResponse)
}

inline void GetLedgerDataResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ledger_hash_){}
    , decltype(_impl_.marker_){}
    , decltype(_impl_.ledger_objects_){nullptr}
    , decltype(_impl_.ledger_index_){0u}
    , decltype(_impl_.is_unlimited_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.ledger_hash_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ledger_hash_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.marker_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.marker_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GetLedgerDataResponse::~GetLedgerDataResponse() {
  // @@protoc_insertion_point(destructor:org.xrpl.rpc.v1.GetLedgerDataResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetLedgerDataResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ledger_hash_.Destroy();
  _impl_.marker_.Destroy();
  if (this != internal_default_instance()) delete _impl_.ledger_objects_;
}

void GetLedgerDataResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetLedgerDataResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:org.xrpl.rpc.v1.GetLedgerDataResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ledger_hash_.ClearToEmpty();
  _impl_.marker_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.ledger_objects_ != nullptr) {
    delete _impl_.ledger_objects_;
  }
  _impl_.ledger_objects_ = nullptr;
  ::memset(&_impl_.ledger_index_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.is_unlimited_) -
      reinterpret_cast<char*>(&_impl_.ledger_index_)) + sizeof(_impl_.is_unlimited_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetLedgerDataResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 ledger_index = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.ledger_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes ledger_hash = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_ledger_hash();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .org.xrpl.rpc.v1.RawLedgerObjects ledger_objects = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_ledger_objects(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes marker = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_marker();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_unlimited = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.is_unlimited_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetLedgerDataResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:org.xrpl.rpc.v1.GetLedgerDataResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ledger_index = 1;
  if (this->_internal_ledger_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_ledger_index(), target);
  }

  // bytes ledger_hash = 2;
  if (!this->_internal_ledger_hash().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_ledger_hash(), target);
  }

  // .org.xrpl.rpc.v1.RawLedgerObjects ledger_objects = 3;
  if (this->_internal_has_ledger_objects()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::ledger_objects(this),
        _Internal::ledger_objects(this).GetCachedSize(), target, stream);
  }

  // bytes marker = 4;
  if (!this->_internal_marker().empty()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_marker(), target);
  }

  // bool is_unlimited = 7;
  if (this->_internal_is_unlimited() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(7, this->_internal_is_unlimited(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:org.xrpl.rpc.v1.GetLedgerDataResponse)
  return target;
}

size_t GetLedgerDataResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:org.xrpl.rpc.v1.GetLedgerDataResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes ledger_hash = 2;
  if (!this->_internal_ledger_hash().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_ledger_hash());
  }

  // bytes marker = 4;
  if (!this->_internal_marker().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_marker());
  }

  // .org.xrpl.rpc.v1.RawLedgerObjects ledger_objects = 3;
  if (this->_internal_has_ledger_objects()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.ledger_objects_);
  }

  // uint32 ledger_index = 1;
  if (this->_internal_ledger_index() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_ledger_index());
  }

  // bool is_unlimited = 7;
  if (this->_internal_is_unlimited() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetLedgerDataResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetLedgerDataResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetLedgerDataResponse::GetClassData() const { return &_class_data_; }


void GetLedgerDataResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetLedgerDataResponse*>(&to_msg);
  auto& from = static_cast<const GetLedgerDataResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:org.xrpl.rpc.v1.GetLedgerDataResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_ledger_hash().empty()) {
    _this->_internal_set_ledger_hash(from._internal_ledger_hash());
  }
  if (!from._internal_marker().empty()) {
    _this->_internal_set_marker(from._internal_marker());
  }
  if (from._internal_has_ledger_objects()) {
    _this->_internal_mutable_ledger_objects()->::org::xrpl::rpc::v1::RawLedgerObjects::MergeFrom(
        from._internal_ledger_objects());
  }
  if (from._internal_ledger_index() != 0) {
    _this->_internal_set_ledger_index(from._internal_ledger_index());
  }
  if (from._internal_is_unlimited() != 0) {
    _this->_internal_set_is_unlimited(from._internal_is_unlimited());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetLedgerDataResponse::CopyFrom(const GetLedgerDataResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:org.xrpl.rpc.v1.GetLedgerDataResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetLedgerDataResponse::IsInitialized() const {
  return true;
}

void GetLedgerDataResponse::InternalSwap(GetLedgerDataResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ledger_hash_, lhs_arena,
      &other->_impl_.ledger_hash_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.marker_, lhs_arena,
      &other->_impl_.marker_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetLedgerDataResponse, _impl_.is_unlimited_)
      + sizeof(GetLedgerDataResponse::_impl_.is_unlimited_)
      - PROTOBUF_FIELD_OFFSET(GetLedgerDataResponse, _impl_.ledger_objects_)>(
          reinterpret_cast<char*>(&_impl_.ledger_objects_),
          reinterpret_cast<char*>(&other->_impl_.ledger_objects_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GetLedgerDataResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto_getter, &descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto_once,
      file_level_metadata_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace rpc
}  // namespace xrpl
}  // namespace org
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::org::xrpl::rpc::v1::GetLedgerDataRequest*
Arena::CreateMaybeMessage< ::org::xrpl::rpc::v1::GetLedgerDataRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::org::xrpl::rpc::v1::GetLedgerDataRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::org::xrpl::rpc::v1::GetLedgerDataResponse*
Arena::CreateMaybeMessage< ::org::xrpl::rpc::v1::GetLedgerDataResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::org::xrpl::rpc::v1::GetLedgerDataResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
