version: 2
build:
  os: ubuntu-22.04
  apt_packages:
    - gcc
    - g++
python:
  version: 3.8
  install:
    - method: pip
      path: python/
sphinx:
  builder: html
  configuration: python/docs/conf.py

submodules:
  include:
    - external/rippled/
