# NOTE: This doesn't work
version: 2
build:
  os: ubuntu-22.04
  apt_packages:
    - gcc
  tools:
    python: "3.11"
python:
  install:
    - method: pip
      path: python/
sphinx:
  builder: html
  configuration: python/docs/conf.py

submodules:
  include:
    - external/rippled/
